# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9fe1dbb5a2c7c1ae86de09f53043159a"
name = "sustainable-partnership-app"
handle = "sustainable-partnership-app-7"
application_url = "https://taken-burton-mathematical-informed.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "watersstore.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://taken-burton-mathematical-informed.trycloudflare.com/auth/callback",
  "https://taken-burton-mathematical-informed.trycloudflare.com/auth/shopify/callback",
  "https://taken-burton-mathematical-informed.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
